### ISSUE TITLE
Order of files in archive requires saving streams to temp

### ISSUE THREAD

**Issue by DaSpawn** [DaSpawn/xlsx-stream-reader#1]
If the worksheets are before the shared strings in the XLSX zip archive the sheet will throw an error as it is impossible to handle the sheets properly without shared strings

best solution is to place each workbook stream into a temp file if the worksheets appear before the shared strings

I only encountered this so far trying to import a sheet created with the streaming writer in guyonroche/exceljs, XLSX files created in open office or excel appear fine so far

in the meantime going to throw error until redirect to temp file is complete.  expected this but did not run into till just now

**Comment by chriszs** [comment]
Here's the hacky solution I used in the mean time:

```javascript
// do a first pass to read shared strings
var workBookReader = new XlsxStreamReader();

workBookReader.on('error', function (error) {
    throw(error);
});

var workBookSharedStrings = [];

workBookReader.on('sharedStrings', function () {
    workBookSharedStrings = workBookReader.workBookSharedStrings;
});

workBookReader.on('worksheet', function (workSheetReader) {
     workSheetReader.skip();
});

workBookReader.on('end',function () {
    // do a second pass to read worksheets
    var workBookReader2 = new XlsxStreamReader();

    workBookReader2.workBookSharedStrings = workBookSharedStrings;

    workBookReader2.on('worksheet', function (workSheetReader) {
        workSheetReader.on('row', function (row) {
            // process row
        });

        workSheetReader.process();
    });

    fs.createReadStream(file)
        .pipe(workBookReader2);
});

fs.createReadStream(file)
    .pipe(workBookReader);
```
