### ISSUE TITLE
How to handle empty sheets

### ISSUE THREAD

**Issue by ghost** [DaSpawn/xlsx-stream-reader#10]
Is there an appropriate way to handle empty sheets? I consistently get a "TypeError: Cannot set property 'values' of undefined". This is the cause:

switch(nodeData[0].name){
...
case 'row':
...
**self.workingRow.values = [];**

**Comment by sb4singh** [comment]
I have the same problem ghost did you find any solution.

**Comment by kikill95** [comment]
Sample can be found in this package: https://www.npmjs.com/package/ek-xls-stream-reader
