### ISSUE TITLE
Wrong value reading .

### ISSUE THREAD

**Issue by Bikasa** [DaSpawn/xlsx-stream-reader#14]
Hi @DaSpawn  ,
 I am trying to read values like "**($500)**" in my sheet .But I observed ,it is reading the value  as "**-500**" .But my requirement is it should read it as "**($500)**".I have attached the sheet below .Please Have a look .

Thanks 
Bikash
[1newSheet.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/1597429/1newSheet.xlsx)

**Comment by DaSpawn** [comment]
Looking at the sheet source (unzip and looking at zl/worksheets/sheet1.xml), the raw value within the sheet is -500 (<c r="B2" s="1"><v>-500</v>)

What you are seeing is cell formatting as a Number ("$"#,##0_);[RED]("$"#,##0)).  If you clear the direct formatting you will see the raw value.
