### ISSUE TITLE
Capability to process only first row of each sheet

### ISSUE THREAD

**Issue by quetzaluz** [DaSpawn/xlsx-stream-reader#15]
I understand if this can't be implemented because it defeats the purpose of streaming, but is there a means of processing the first row of each worksheet? Looks like you can't call `workSheetReader.skip()` within the `row` processing handler for instance that might allow for early break out of streaming once the first row of every worksheet has been processed. I am working with very large files where only the first row needs to be considered for initial processing and it's fine if there is no means of parsing only the first row.

**Comment by quetzaluz** [comment]
I've found calling `workSheetReader.abort()` instead of `workSheetReader.skip()` within the `row` handler achieves what I wanted to achieve more or less. Thank you for developing this module by the way!

**Comment by DaSpawn** [comment]
skipping the worksheet will just read past that sheet and look for the next in the zip stream, so the file stream must be read anyway.  

if you need any rows from the sheet you will need to still handle the row events, just process the first row event and return from the function for the remaining rows.  

you should not use workSheetReader.abort() as it will only abort the stream at the point it has reached and could already be in the middle of processing rows in the xml.  You can not rely on anything once you call abort().  Using workSheetReader.skip() actually calls the skip function in the zip processor so absolutely none of the sheet will be received by the xml handler
