### ISSUE TITLE
Date values parsed in wrong format

### ISSUE THREAD

**Issue by kikill95** [DaSpawn/xlsx-stream-reader#18]
Hello, @DaSpawn thank you for a great work with this package. I've looked deeply in it and tried several documents. There is my fork: https://github.com/kikill95/xlsx-stream-reader

Can you please take a look and let me know what is wrong?

I am working with `example/example4.js` and `example/example5.xlsx` files. In `workBookReader.workBookSharedStrings` I got the following:

    [ 'a', 'b', 'c', '11/04/2014', '04/01/2016' ]

But I believe this should be

    [ 'a', 'b', 'c', '09/01/1981', '11/04/2014', '04/01/2016' ]

And on 'row' for workSheetReader I received in "row.values" something strange instead of '09/01/1981': I got this: "29595"

I know that you had experienced with this more than me, so maybe this is easy for you to recognize where is the issue.

p.s. I have tried your master branch and received the same results

**Comment by kikill95** [comment]
Also, I saw one another issue https://github.com/DaSpawn/xlsx-stream-reader/issues/8
I tried to resave (and even reexport), but same issue here =(

p.s.s. in my fork I've also fixed https://github.com/DaSpawn/xlsx-stream-reader/issues/13 and https://github.com/DaSpawn/xlsx-stream-reader/issues/11 and this https://github.com/DaSpawn/xlsx-stream-reader/issues/10

**Comment by DaSpawn** [comment]
Interesting issue..  I did see this in the past, I will have to revisit as soon as I can

Thank you for looking at/working on those issues.  I have been incredibly busy with work, would you like to bring your changes into this project/be added as a collaborator?

**Comment by lambrojos** [comment]
Sorry if I comment on a closed issue, but may I ask if you could publish the 1.0.0 version on npm? @DaSpawn

**Comment by DaSpawn** [comment]
I published to NPM (had to bump to version 1.0.1 first)

**Comment by lambrojos** [comment]
Thank you ! 👍
