### ISSUE TITLE
Cannot read several files in parallel

### ISSUE THREAD

**Issue by Magomogo** [DaSpawn/xlsx-stream-reader#36]
We've experienced problems running several xlsx-stream-readers simultaneously.

After one stream is finished, the another one gets crashed with the message:

        Error: ENOENT: no such file or directory, open '/tmp/s-1181119-1485-on5bzr.ok4ir'

I suspect the reason is misusage of https://github.com/bruce/node-temp library. After first file is finished the `temp.cleanup()` invocation cleanups the `/tmp/` files that are in use by the second process.

Could you confirm that? Can we use some [affixes](https://github.com/bruce/node-temp#affixes) to isolate the processes?

**Comment by spunith777** [comment]
@Magomogo facing the same issue. any update on how to handle this issue?

**Comment by DaSpawn** [comment]
Looks like the temp module will need to be changed.  I have been incredibly busy and can not do at the moment.  Will do soon as I can
