### ISSUE TITLE
Getting wrong .CSV file while converting .XLSX to .CSV

### ISSUE THREAD

**Issue by Bikasa** [DaSpawn/xlsx-stream-reader#4]
Hi @DaSpawn ,
  For a particular file I am getting  wrong data for CSV  after converting .xlsx to .csv.  May I know the reason ,Why my module takes wrong column data for while converting the xlsx file.I have attached the .xlsx file as well as the out put .csv file in the Zip file. After debugging I have observed that at line no 10 of the excell sheet the  2nd coumn value is coming from the 3rd column value of line no 9 of excel . May I know the reason for this issue.  

[one.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/608648/one.xlsx)

[one.zip](https://github.com/DaSpawn/xlsx-stream-reader/files/608649/one.zip)

![errorexcel](https://cloud.githubusercontent.com/assets/23119692/20559449/819eb096-b19a-11e6-8349-fb646f77866d.png)

**Comment by Bikasa** [comment]
Sorry ..I observed the file was a corrupted file..Now its working as expected..

**Comment by DaSpawn** [comment]
If I use your xlsx sheet with the example the columns are returned properly as indexed:

`RowNum 10 colNum 1 rowValLen 3 rowVal '900'`
`RowNum 10 colNum 2 rowValLen 21 rowVal 'Tiered Royalty Band 3'`
`RowNum 10 colNum 4 rowValLen 6 rowVal '804100'`
`RowNum 10 colNum 5 rowValLen 15 rowVal 'IP Cost Sharing'`
`RowNum 10 colNum 6 rowValLen 0 rowVal ''`
`RowNum 10 colNum 12 rowValLen 3 rowVal 'TPR'`
`RowNum 10 colNum 13 rowValLen 24 rowVal 'MIPCS (not recorded yet)'`
`RowNum 10 colNum 14 rowValLen 9 rowVal 'Principal'`

rows are sparse arrays, you need to be sure to use the element index and not just blindly itterate through the rows as any empty cells will not be set in the array (see https://github.com/DaSpawn/xlsx-stream-reader/blob/master/example/example1.js#L31 the colNum variable)
