### ISSUE TITLE
WorkSheetReader Row Event not fired for all rows

### ISSUE THREAD

**Issue by gnanaprakash** [DaSpawn/xlsx-stream-reader#43]
Not receiving the row events as per the row, at times row event start with an arbitrary row data in the sheet 

(file removed)
 data in attached excel

**Comment by DaSpawn** [comment]
I will take a look (I removed the file from the issue as it appears to have personal/sensitive information)

**Comment by DaSpawn** [comment]
I just did a quick test and my results are 20,000 entries long

const XlsxStreamReader = require('./xlsx-stream-reader')
const fs = require('fs')
const path = require('path')

const workBookReader = new XlsxStreamReader()
fs.createReadStream(path.join(__dirname, 'C.Data.2.scholars.xlsx')).pipe(workBookReader)
const rows = []
workBookReader.on('worksheet', function (workSheetReader) {
  workSheetReader.on('end', function () {
  	console.log("rows.length",rows.length,rows[0]);
  })
  workSheetReader.on('row', function (r) {
    rows.push(r.values)
  })
  workSheetReader.process()
})

Please reopen with more details if this is still an issue
