### ISSUE TITLE
"0"  becomes ' '

### ISSUE THREAD

**Issue by epabhishek** [DaSpawn/xlsx-stream-reader#44]
Recently our client was complaining that he is not able to upload 0 as values. We checked that 0 was converted to ' '. When we edit the cell and again save it as 0. It is not converted to ' '. But when we directly download the file from attachments  and upload it to system 0 is becoming  ' '.

**Comment by jesnil01** [comment]
@epabhishek experiencing the same issue, did you find any solution to this?

**Comment by DaSpawn** [comment]
I have pushed the fixes, will bump npm version soon
