### ISSUE TITLE
Pausing Stream While Processing Data

### ISSUE THREAD

**Issue by valeeum** [DaSpawn/xlsx-stream-reader#5]
You mention in the documentation that the stream can be paused.  I know it's not tested but how would you go about doing so?

**Comment by DaSpawn** [comment]
If you are piping a stream into the reader, while you are reading/processing you could .pause() the stream till you are ready to read more

If you are still interested I can try to make an example to confirm if it even will work as expected

**Comment by valeeum** [comment]
I tried with my limited understanding at the time and couldn't get it to work.  An example would be great.

**Comment by DaSpawn** [comment]
looks like pausing the input stream is useless/problematic.  The only way I have been able to pause processing is while reading the cells and hundreds of cell events can still happen after the pause

if this is still useful I will push the example I have worked on which also requires updating the module to add pause/resume functions

**Comment by shaunc** [comment]
This would be great ... should I open another issue? This library looks promising for what I need, but if processing a large xlsx (e.g. to save to a database) I need some sort of backpressure mechanism to insure that memory use is constrained until done saving a chunk of data. (Another possibility is for the worksheet object to be a stream of rows, so stream backpressure could be used.)

**Comment by jansivans** [comment]
If someone needs pause functionality, I've created lib that can do this - https://github.com/Claviz/xlstream.
