### ISSUE TITLE
file column data is not reading properly

### ISSUE THREAD

**Issue by jofinkuriakose** [DaSpawn/xlsx-stream-reader#53]
I am attaching one file for reference
The data which I am getting the issue is in C3

The data reads as follows,
Header row: Fname,Lname,Emails
1st row: Winemiller,Jonathan,jwinemiller@walthew.com
2nd row: Buckley,James, (wrong data - not able to read email: jbuckley@buckleylaw.net)
[test201.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/4757776/test201.xlsx)

**Comment by DaSpawn** [comment]
I just did a test and looks like the value is in the row results as expected:

const XlsxStreamReader = require('./xlsx-stream-reader')
const fs = require('fs')
const path = require('path')

const workBookReader = new XlsxStreamReader()
fs.createReadStream(path.join(__dirname, 'test201.xlsx')).pipe(workBookReader)
const rows = []
workBookReader.on('worksheet', function (workSheetReader) {
  workSheetReader.on('end', function () {
  	console.log("rows.length",rows.length,rows[3]);
  })
  workSheetReader.on('row', function (r) {
    rows.push(r.values)
  })
  workSheetReader.process()
})

Please reopen if this is still an issue
