### ISSUE TITLE
For Small decimal values workSheetReader.on('row', function (row) {}  reading incorrectly

### ISSUE THREAD

**Issue by Bikasa** [DaSpawn/xlsx-stream-reader#6]
Hi @DaSpawn ,
 I am trying to read the decimal values like 0.4082 from my excel file and it returns me the value like 0.4082000000000001 ..which I don't want.  I have attached the screen shot for this.Can you please find the issue with this module and let me know the solution for this.
![issue](https://cloud.githubusercontent.com/assets/23119692/23505746/07deaaf8-ff6b-11e6-8db5-d25420ee0d0d.png)

Thanks 
Bikash

**Comment by DaSpawn** [comment]
Can you provide the source doc you are working with?  (I have not run into this and I work with numbers constantly)

**Comment by Bikasa** [comment]
@DaSpawn ,please find the attached file
[Product.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/817317/Product.xlsx)

**Comment by DaSpawn** [comment]
Looking at the source for xl/worksheets/sheet1.xml within the docx zip archive:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
	<dimension ref="A1:B4"/>
	<sheetViews>
		<sheetView tabSelected="1" workbookViewId="0">
			<selection activeCell="B4" sqref="B4"/>
		</sheetView>
	</sheetViews>
	<sheetFormatPr defaultRowHeight="14.4"/>
		<sheetData>
			<row r="1" spans="1:2">
				<c r="A1" t="s">
					<v>0</v>
				</c>
				<c r="B1" t="s">
					<v>1</v>
				</c>
			</row>
			<row r="2" spans="1:2">
				<c r="A2" t="s">
					<v>3</v>
				</c>
				<c r="B2">
					<v>0.40820000000000001</v>
				</c>
			</row>
			<row r="3" spans="1:2">
				<c r="A3" t="s">
					<v>2</v>
				</c>
				<c r="B3">
					<v>8.4000000000000003E-4</v>
				</c>
			</row>
			<row r="4" spans="1:2">
				<c r="A4" t="s">
					<v>4</v>
				</c>
				<c r="B4">
					<v>3.0084</v>
				</c>
			</row>
		</sheetData>
	<pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>
</worksheet>
```

the cell values for B2 is actually 0.40820000000000001 but it appears excel may be rounding the values whereas this module does not round field values (that is left to the user)

I would recommend rounding your values to the length used/displayed in excel as needed (I can not find another answer to why this is even happening/excel would do this)

**Comment by Bikasa** [comment]
@DaSpawn  ok ,thank you .But since I am working with currency calculation ..i can't apply round up.

**Comment by DaSpawn** [comment]
Understandable, but I suspect Excel already does the rounding as the number you are seeing is actually stored in the excel value data but Excel presents a rounded number based on field settings.  If that cell was a calculated field originally the value has been calculated and stored by Excel in the sheet data, this module does not do any handling/calculation of formulas

I can across this, maybe it is there but just not visible: https://support.office.com/en-us/article/Change-the-decimal-places-displayed-for-numbers-89195539-878f-4710-8801-196af8cc94ac
