### ISSUE TITLE
getting error while reading the excel file having formula defined for a column

### ISSUE THREAD

**Issue by Bikasa** [DaSpawn/xlsx-stream-reader#7]
Hi @DaSpawn ,
  I am getting issue while I am trying to import the below file.What I observe some formula is set for the  column E and column F .While I am trying  read the file using the module I am getting the below error.

**" message: 'uncaught Exception: \'TypeError: Cannot read property \\\'r\\\' of undefined\\n    at XlsxStreamReaderWorkSheet._handleW/services/ooxp-service-fileimport/1.0.0/console-file-reader/node_modules/xlsx-stream-reader/lib/worksheet.js:238:66)\\n    at SAXStream.<anonymous> (/appserver/serviort/1.0.0/console-file-reader/node_modules/xlsx-stream-reader/lib/workbook.js:224:17)\\n    at emitOne (events.js:77:13)\\n    at SAXStream.emit (events.js:169:7)\\n.(anonymous function) [as onclosetag]"**

I am not sure whether this is the actual reason or not . I have attached the file that I am using along with the screen shoot of the column where a formula is used  depending another column value.Can you please have a look on the issue and let me know if any solution available for this scenario.

![node module issue](https://cloud.githubusercontent.com/assets/23119692/24001270/b3a1a318-0a83-11e7-8098-ac5be14bf36d.png)

[prod6331small.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/847914/prod6331small.xlsx)

Thanks
Bikash

**Comment by DaSpawn** [comment]
this module does not have any formula handling, I will have to try this later and fix the error as you should still not receive a fatal exception like that.  Usually Excel will store the calculated values when saving the sheet, this may be a different case

**Comment by DaSpawn** [comment]
I need to know how you generated prod6331small.xlsx because there is something not right with that sheet that eliminates the error if I only open and re-save that xlsx in Excel

I still need to add better error handling in that instance as it is still possible to get the data out of the sheet obviously if Excel can fix it.

**Comment by Bikasa** [comment]
@DaSpawn  I have attached a  new excel sheet (FormulaExcel.xlsx) .Can you check whit this sheet.I think this will help you to fix the issue.
[FormulaExcel.xlsx](https://github.com/DaSpawn/xlsx-stream-reader/files/857611/FormulaExcel.xlsx)

**Comment by DaSpawn** [comment]
The latest npm version should now fix the issues (0.9.9).  I used prod6331small.xlsx as examples/example2.xlsx, and I tried using FormulaExcel.xlsx in the example yields:

Worksheet: 1
RowNum 1 colNum 1 rowValLen 2 rowVal 'A1'
RowNum 1 colNum 2 rowValLen 2 rowVal 'A2'
RowNum 1 colNum 3 rowValLen 2 rowVal 'A3'
RowNum 2 colNum 1 rowValLen 4 rowVal 'val1'
RowNum 2 colNum 2 rowValLen 2 rowVal '25'
RowNum 2 colNum 3 rowValLen 1 rowVal '5'
Worksheet 1 rowCount: 2

Please let me know if 0.9.9 fixes issues

**Comment by Bikasa** [comment]
@DaSpawn , Thanks ..It's working fine for me.
